version: "3"
services:

  backend:
    build: ./vote-api
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_HOST=database
    ports: 
      - 4000:4000
    depends_on:
      - database
    links:
      - database
      
  database:
    image: postgres:16.3
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: on-failure